#!/usr/bin/env bash
#
# fix-ncurses-makefiles.sh — run after ncurses configure to patch missing rules
# Usage: fix-ncurses-makefiles.sh <ncurses_build_dir>
#
set -e
AWK="${AWK:-gawk}"
BUILD_DIR="${1:?usage: $0 <ncurses-build-dir>}"
cd "$BUILD_DIR"

mkdir -p objects lib progs/objects

# ---- detect build config from config.status (always do this) ----
LIB_SUFFIX_VAL=$(grep '^LIB_SUFFIX=' config.status 2>/dev/null | sed 's/.*=//;s/"//g')
USE_LIB_SUFFIX_VAL=$(grep '^USE_LIB_SUFFIX=' config.status 2>/dev/null | sed 's/.*=//;s/"//g')
LIB_NAME_VAL=$(grep '^LIB_NAME=' config.status 2>/dev/null | sed 's/.*=//;s/"//g')
: "${LIB_NAME_VAL:=ncurses}"

# Check if rules already exist (configure succeeded in generating them)
RULES_EXIST=no
if grep -q 'generated by mk-1st' ncurses/Makefile 2>/dev/null; then
	RULES_EXIST=yes
fi

echo "fix-ncurses-makefiles.sh: rules_exist=$RULES_EXIST LIB_SUFFIX=$LIB_SUFFIX_VAL"

if [ "$RULES_EXIST" = yes ]; then
	echo "fix-ncurses-makefiles.sh: skipping lib rules (already in Makefile)"
else
	# Configure did NOT generate rules — need to add everything.
	LN_S=$(grep '^LN_S=' config.status 2>/dev/null | sed 's/.*=//;s/"//g')
	SHLIB_VER=$(grep '^cf_cv_shlib_version=' config.status 2>/dev/null | sed 's/.*=//;s/"//g')
	SHLIB_VER_INFIX=$(grep '^cf_cv_shlib_version_infix=' config.status 2>/dev/null | sed 's/.*=//;s/"//g')
	LIB_SUBSETS_VAL=$(grep '^LIB_SUBSETS=' config.status 2>/dev/null | sed 's/.*=//;s/"//g')
	: "${LN_S:=ln -s -f}"
	: "${SHLIB_VER:=abi}"
	: "${SHLIB_VER_INFIX:=yes}"
	: "${LIB_SUBSETS_VAL:=termlib+ext_tinfo+base+ext_funcs}"

	if [ -n "$USE_LIB_SUFFIX_VAL" ]; then
		LIBRARY_NAME="${LIB_NAME_VAL}${USE_LIB_SUFFIX_VAL}"
	else
		LIBRARY_NAME="${LIB_NAME_VAL}"
	fi

	WITH_SHARED=no
	if grep -q '^s,@MK_SHARED_LIB@,' config.status 2>/dev/null; then
		WITH_SHARED=yes
	fi

	HOST_SYS=$(grep '^host=' config.status 2>/dev/null | sed "s/.*=//;s/'//g")
	case "$HOST_SYS" in
		*-darwin*) SHARED_SUFFIX=.dylib ;;
		*) SHARED_SUFFIX=.so ;;
	esac

	echo "fix-ncurses-makefiles.sh: LIBRARY=$LIBRARY_NAME shared=$WITH_SHARED shared_suffix=$SHARED_SUFFIX"

	run_mk1st() {
		local name="$1" dir="$2" subset="$3" model_item="$4" suffix="$5" depend="$6"
		local model_subdir
		case "$model_item" in
			NORMAL)  model_subdir=objects ;;
			SHARED)  model_subdir=obj_s ;;
			*) model_subdir=objects ;;
		esac
		mkdir -p "$model_subdir"
		$AWK -f mk-1st.awk \
			name="$name" \
			traces=DEBUG \
			MODEL="$model_item" \
			CXX_MODEL="$model_item" \
			LIB_SUFFIX="${LIB_SUFFIX_VAL}" \
			USE_LIB_SUFFIX="${USE_LIB_SUFFIX_VAL}" \
			make_phony=yes \
			model="$model_subdir" \
			prefix=lib \
			suffix="$suffix" \
			subset="$subset" \
			driver=no \
			SymLink="$LN_S" \
			TermlibRoot=ncurses \
			TermlibSuffix="${SHARED_SUFFIX}" \
			ShlibVer="$SHLIB_VER" \
			ShlibVerInfix="$SHLIB_VER_INFIX" \
			ReLink=no \
			ReRanlib=yes \
			DoLinks=yes \
			rmSoLocs=no \
			ldconfig="" \
			overwrite=no \
			depend="$depend" \
			host="" \
			libtool_version="" \
			"$dir/modules" >> "$dir/Makefile"
	}

	run_mk2nd() {
		local name="$1" dir="$2" subset="$3" model_item="$4"
		local model_subdir
		case "$model_item" in
			NORMAL)  model_subdir=objects ;;
			SHARED)  model_subdir=obj_s ;;
			*) model_subdir=objects ;;
		esac
		$AWK -f mk-2nd.awk \
			name="$name" \
			traces=DEBUG \
			MODEL="$model_item" \
			model="$model_subdir" \
			subset="$subset" \
			srcdir=. \
			echo=yes \
			crenames=yes \
			cxxrenames=yes \
			"$dir/modules" >> "$dir/Makefile"
	}

	gen_rules() {
		local libname="$1" dir="$2" subset="$3" depend="$4"
		run_mk1st "$libname" "$dir" "$subset" NORMAL .a "$depend"
		run_mk2nd "$libname" "$dir" "$subset" NORMAL
		if [ "$WITH_SHARED" = yes ]; then
			# Always generate shared link rule + compilation rules.
			# The configure on macOS often fails to generate SHARED rules
			# even though "Appending rules for shared model" is echoed.
			run_mk1st "$libname" "$dir" "$subset" SHARED "$SHARED_SUFFIX" "$depend"
			run_mk2nd "$libname" "$dir" "$subset" SHARED
		fi
	}

	NC_DEPS="../include/ncurses_cfg.h \${srcdir}/curses.priv.h"
	gen_rules "$LIBRARY_NAME" ncurses "$LIB_SUBSETS_VAL" "$NC_DEPS"
	# ticlib: only static (NORMAL), the shared lib links ticlib objects
	# via TICS_LIST generated by the main gen_rules SHARED pass
	run_mk1st "$LIBRARY_NAME" ncurses "ticlib" NORMAL .a "$NC_DEPS"
	run_mk2nd "$LIBRARY_NAME" ncurses "ticlib" NORMAL

	for d in panel menu form; do
		dir_name="${d}${LIB_SUFFIX_VAL}"
		gen_rules "$dir_name" "$d" "$LIB_SUBSETS_VAL" ""
	done

	# c++ binding (if directory exists and needs rules)
	if [ -d c++ ] && [ -f c++/modules ]; then
		cxx_name=$(grep '^CXX_NAME=' config.status 2>/dev/null | sed 's/.*=//;s/"//g')
		[ -z "$cxx_name" ] && cxx_name="ncurses++"
		cxx_name="${cxx_name}${USE_LIB_SUFFIX_VAL}"
		rm -rf "${cxx_name}"
		ln -sf c++ "${cxx_name}" 2>/dev/null || true
		gen_rules "$cxx_name" c++ "$LIB_SUBSETS_VAL" ""
	fi
fi

# ---- wide-char symlink fixes (always needed when --enable-widec) ----
if echo "$LIB_SUFFIX_VAL" | grep -q 'w'; then
	# Create source directory symlinks (ncursesw -> ncurses, etc.)
	for d in ncurses panel menu form c++; do
		[ -d "$d" ] || continue
		[ -L "${d}w" ] || { rm -rf "${d}w"; ln -sf "$d" "${d}w"; }
	done
	# c++ also needs a named symlink (e.g., ncurses++w -> c++)
	cxx_name=$(grep '^CXX_NAME=' config.status 2>/dev/null | sed 's/.*=//;s/"//g')
	if [ -n "$cxx_name" ] && [ -d c++ ]; then
		cxx_link="${cxx_name}${USE_LIB_SUFFIX_VAL}"
		[ -L "$cxx_link" ] || { rm -rf "$cxx_link"; ln -sf c++ "$cxx_link"; }
	fi

	# Add compat symlink rules for shared libraries
	for d in ncurses panel menu form; do
		base="${d}"
		if ! grep -q "lib${base}.so\..*REL_VERSION.*lib${base}w" "$d/Makefile" 2>/dev/null; then
			[ -f "$d/Makefile" ] || continue
			cat >> "$d/Makefile" << EOF

# Symlink for non-wide -> wide compatibility (added by fix-ncurses-makefiles.sh)
../lib/lib${base}.so.\$(REL_VERSION) : ../lib/lib${base}w.so.\$(REL_VERSION)
	@echo "creating compatibility symlink \$@"
	cd ../lib && (\$(LN_S) lib${base}w.so.\$(REL_VERSION) lib${base}.so.\$(REL_VERSION); \$(LN_S) lib${base}.so.\$(REL_VERSION) lib${base}.so.\$(ABI_VERSION); \$(LN_S) lib${base}.so.\$(ABI_VERSION) lib${base}.so; )
EOF
			echo "fix-ncurses-makefiles.sh: added $base compat symlink rule"
		fi
	done
fi

# ---- progs: manual rules for tic (always needed) ----
if ! grep -q 'fix-ncurses-makefiles\.sh.*rules for tic' progs/Makefile 2>/dev/null; then
	cat >> progs/Makefile << 'EOF'

# Added by fix-ncurses-makefiles.sh — rules for tic
../objects/tic$o: $(srcdir)/tic.c $(HEADER_DEPS) transform.h
	$(LIBTOOL_COMPILE) $(CC) $(CFLAGS_NORMAL) -c $(srcdir)/tic.c -o $@

../objects/dump_entry$o: $(srcdir)/dump_entry.c $(HEADER_DEPS) termsort.h
	$(LIBTOOL_COMPILE) $(CC) $(CFLAGS_NORMAL) -c $(srcdir)/dump_entry.c -o $@

../objects/tparm_type$o: $(srcdir)/tparm_type.c $(HEADER_DEPS)
	$(LIBTOOL_COMPILE) $(CC) $(CFLAGS_NORMAL) -c $(srcdir)/tparm_type.c -o $@

../objects/transform$o: $(srcdir)/transform.c $(HEADER_DEPS) transform.h
	$(LIBTOOL_COMPILE) $(CC) $(CFLAGS_NORMAL) -c $(srcdir)/transform.c -o $@
EOF
fi

# Generate termsort.h if needed
if [ ! -f progs/termsort.h ]; then
	sh progs/MKtermsort.sh "$AWK" include/Caps > progs/termsort.h
fi

# ---- install.includes fix: ensure term.h gets installed ----
# ncurses' install.includes only copies curses.h/unctrl.h/ncurses_dll.h,
# but term.h (containing setupterm/cur_term/del_curterm) is NOT installed.
# Add the recipe line to the include/Makefile install.includes target.
INC_MAKEFILE="include/Makefile"
if [ -f "$INC_MAKEFILE" ] && ! grep -q 'term\.h.*headers\.sh' "$INC_MAKEFILE" 2>/dev/null; then
	# Insert term.h install command after the ncurses_dll.h install line
	ed -s "$INC_MAKEFILE" << 'EDEOF'
/INSTALL_DATA}.*ncurses_dll\.h/a
	@ (cd ${INCLUDEDIR} && rm -f term.h) ; ../headers.sh ${INSTALL_DATA} ${INCLUDEDIR} ${srcdir} term.h
.
w
q
EDEOF
	echo "fix-ncurses-makefiles.sh: added term.h to install.includes"
fi

echo "fix-ncurses-makefiles.sh: done."
